# Generated by Selenium IDE
import pytest
import time
import json

from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestUntitled():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_untitled(self):
    # Test name: Untitled
    # Step # | name | target | value
    # 1 | open | /Online/Portal/Index/7716 | 
    self.driver.get("https://app.courtreserve.com/Online/Portal/Index/7716")
    # 2 | setWindowSize | 1419x1602 | 
    self.driver.set_window_size(1419, 1602)
    # 3 | click | linkText=Log out | 
    self.driver.find_element(By.LINK_TEXT, "Log out").click()
    # 4 | click | linkText=LOG IN | 
    self.driver.find_element(By.LINK_TEXT, "LOG IN").click()
    # 5 | type | id=UserNameOrEmail | mdonthireddy@gmail.com
    self.driver.find_element(By.ID, "UserNameOrEmail").send_keys("mdonthireddy@gmail.com")
    # 6 | type | id=Password | <xxxx***xxx>
    self.driver.find_element(By.ID, "Password").send_keys("<xxxx***xxx>")
    # 7 | mouseDownAt | id=UserNameOrEmail | 188.5,20.078125
    element = self.driver.find_element(By.ID, "UserNameOrEmail")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).click_and_hold().perform()
    # 8 | mouseMoveAt | id=UserNameOrEmail | 188.5,20.078125
    element = self.driver.find_element(By.ID, "UserNameOrEmail")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 9 | mouseUpAt | id=UserNameOrEmail | 188.5,20.078125
    element = self.driver.find_element(By.ID, "UserNameOrEmail")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).release().perform()
    # 10 | click | id=UserNameOrEmail | 
    self.driver.find_element(By.ID, "UserNameOrEmail").click()
    # 11 | click | css=.login_form | 
    self.driver.find_element(By.CSS_SELECTOR, ".login_form").click()
    # 12 | click | css=.btn-log | 
    self.driver.find_element(By.CSS_SELECTOR, ".btn-log").click()
    # 13 | click | css=.menu-active .arrow | 
    self.driver.find_element(By.CSS_SELECTOR, ".menu-active .arrow").click()
    # 14 | click | css=#respMenu > .fn-ace-parent-li:nth-child(2) .arrow | 
    self.driver.find_element(By.CSS_SELECTOR, "#respMenu > .fn-ace-parent-li:nth-child(2) .arrow").click()
    # 15 | click | linkText=Mercer County Outdoor Tennis Courts 13-18 | 
    self.driver.find_element(By.LINK_TEXT, "Mercer County Outdoor Tennis Courts 13-18").click()
    # 16 | click | css=.k-i-arrow-60-right | 
    self.driver.find_element(By.CSS_SELECTOR, ".k-i-arrow-60-right").click()
    # 17 | click | css=.k-i-arrow-60-right | 
    self.driver.find_element(By.CSS_SELECTOR, ".k-i-arrow-60-right").click()
    # 18 | click | css=.k-i-arrow-60-right | 
    self.driver.find_element(By.CSS_SELECTOR, ".k-i-arrow-60-right").click()
    # 19 | click | css=tr:nth-child(3) > .k-nonwork-hour:nth-child(2) .btn | 
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(3) > .k-nonwork-hour:nth-child(2) .btn").click()
    # 20 | click | css=.modal-title-buttons:nth-child(1) > .btn-primary | 
    self.driver.find_element(By.CSS_SELECTOR, ".modal-title-buttons:nth-child(1) > .btn-primary").click()
    # 21 | click | css=.btn-light | 
    self.driver.find_element(By.CSS_SELECTOR, ".btn-light").click()
  
